{% set name = "torchrecurrent" %}
{% set version = "0.1.10" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchrecurrent-{{ version }}.tar.gz
  sha256: c438f2d95b5e80cf1057cc4dbf0cb7fa37c3607fed3a70f4082bf106012286ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - torchrecurrent
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MartinuzziFrancesco/torchrecurrent
  summary: A package for recurrent neural networks in PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MartinuzziFrancesco
