{% set name = "torchrecurrent" %}
{% set version = "0.1.11" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torchrecurrent-{{ version }}.tar.gz
  sha256: 175b526145b55d839c44ffe14bb0c80177214accaa535b226618debe336a1786

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - torchrecurrent
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MartinuzziFrancesco/torchrecurrent
  summary: A package for recurrent neural networks in PyTorch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MartinuzziFrancesco
