context:
  version: 0.1.8
  python_min: 3.11

package:
  name: squall-sql
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/s/squall-sql/squall_sql-${{ version }}.tar.gz
    sha256: a6c0adba3e6919e3fb2c05d7f9cce8260b6d8cc1ad5f71cb08ea5ccc7b70d974

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  python:
    entry_points:
      - squall = squall.squall:main
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - rich >=13.9.4
    - sqlalchemy >=2.0.38
    - textual >=2.1.1

tests:
  - script:
      - squall --help

about:
  summary: Squall - SQLite Editor
  homepage: https://github.com/driscollis/squall/
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/driscollis/squall/blob/main/README.md

extra:
  recipe-maintainers:
    - carlodri
