# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.10.0.20250822"

package:
  name: types-parsimonious
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-parsimonious/types_parsimonious-${{ version }}.tar.gz
  sha256: 7a208c713ffc5da8e63ab8d5f9f74e30958c3d9e48a5cca69d78d5e7c395b88d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
  run:
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - mypy
        - parsimonious
        - python ${{ python_min }}.*
    script:
      - mypy -p parsimonious

about:
  summary: Typing stubs for parsimonious
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/python/typeshed/tree/main/stubs/parsimonious

extra:
  recipe-maintainers:
    - bollwyvl
