schema_version: 1

context:
  name: compoundfiles
  version: 0.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/compoundfiles-${{ version }}.tar.gz
  sha256: a435c1053786850a78b74b9ba6a317aab2ae97442d48f3ec5392dc2c51c161e9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - compoundfiles
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Library for parsing and reading OLE Compound Documents
  license: MIT
  license_file: LICENSE
  homepage: https://compound-files.readthedocs.org/
  documentation: https://compound-files.readthedocs.org/
  repository: https://github.com/waveform-computing/compoundfiles

extra:
  recipe-maintainers:
    - jens-ox
