context:
  name: msutils
  version: "0.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/DataAnalyticsEngineering/MSUtils/archive/refs/tags/v${{ version }}.tar.gz
  sha256: B4A2F29E09271FB501169F1B15278E5CA7BEE62D14EB833E16A9E1EA42940438

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - numpy >=1.26.4,<2
    - h5py >=3.15.1,<4
    - scipy >=1.16.2,<2
    - matplotlib >=3.10.7,<4
    - scikit-image >=0.25.2,<0.26
    - lxml >=6.0.2,<7
    - plotly >=6.3.1,<7
    - sympy >=1.14.0,<2
    - ipykernel >=7.0.1,<8
    - quaternion >=2024.0.12,<2025
    - beartype >=0.22.3,<0.23
    - pre-commit >=4.3.0,<5
    - pyvista >=0.46.3,<0.47
    - meshio >=5.3.5,<6
    - nbformat >=5.10.4,<6
    - puma >=3.2.0,<4

tests:
  - python:
      imports:
        - msutils
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/DataAnalyticsEngineering/MSUtils
  summary: 'A collection of utilities for creating, processing and exporting voxelized 3D microstructure image datasets.'
  description: |
    MSUtils is a collection of utilities and scripts for creating, processing and exporting voxelized microstructure data which can be readily used in FFT-based solvers such as FANS.
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  
extra:
  recipe-maintainers:
    - claudiushaag
    - sanathkeshav
    - EMMAOpenSource
