schema_version: 1

context:
    name: polylith-cli
    version: 1.35.0

package:
    name: ${{ name|lower }}
    version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/polylith_cli-${{ version }}.tar.gz
    sha256: af2a08c3a0bb51b40ed67d736a5a8745470b1f2a488955d2b3be60fb5a69ede6
  - url: https://raw.githubusercontent.com/DavidVujic/python-polylith/refs/heads/main/LICENSE
    sha256: cb206b34b119d5e0f3ed4634fa8cafa73b0ef64f390772ee2211880e0730c4a7

build:
    number: 0
    noarch: python
    script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    python:
        entry_points:
            - poly = polylith_cli.polylith.cli.core:app

requirements:
    host:
        - python ${{ python_min }}.*
        - poetry-core
        - pip
    run:
        - python >=${{ python_min }},<4.0.0
        - tomlkit 0.*
        - rich >=13,<15
        - typer 0.*
        - pyyaml

tests:
    - python:
          python_version: ${{ python_min }}.*
          imports:
              - polylith_cli
          pip_check: true
    - requirements:
          run:
              - pip
      script:
          - poly --help

about:
    summary: Python tooling support for the Polylith Architecture
    license: MIT
    homepage: https://davidvujic.github.io/python-polylith-docs/
    repository: https://github.com/DavidVujic/python-polylith

extra:
    recipe-maintainers:
        - FloLangenfeld
