{% set name = "geotessera" %}
{% set version = "0.6.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/geotessera-{{ version }}.tar.gz
  sha256: 33819b649da9c5157a0598b2aad98df9deb2305ffc8904e9a60c8bef536a4ea3

build:
  entry_points:
    - geotessera = geotessera.cli:main
    - geotessera-registry = geotessera.registry_cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >= {{ python_min }}
    - pooch
    - tqdm >=4.67.1
    - numpy
    - geopandas
    - pandas
    - matplotlib-base
    - rasterio
    - sphinx >=8.2.3
    - rich
    - typer
    - geodatasets >=2024.8.0
    - scikit-learn >=1.7.1
    - scikit-image >=0.25.2
    - pyarrow >=17.0.0

test:
  imports:
    - geotessera
  commands:
    - pip check
    - geotessera --help
    - geotessera-registry --help
  requires:
    - pip

about:
  home: https://github.com/ucam-eo/geotessera
  summary: Python library interface to the Tessera geofoundation model embeddings
  description: Python library interface to the Tessera geofoundation model embeddings
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - giswqs
