{% set name = "molviewspec" %}
{% set version = "1.7.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/molviewspec-{{ version }}.tar.gz
  sha256: fe978a8b99359b414dbfb7c5694540f8483aa50ac4e2c648e42766647d72c120

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pydantic >=1,<3

test:
  imports:
    - molviewspec
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/molstar/mol-view-spec
  summary: Generate Mol* views using this simple Python library, which allows you to compose complex scenes in a step-wise manner.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dsehnal
    - standag
